spring:
  application:
    name: 38_SBMS_Circuit_Breaker_App

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      myService:
        # override defaults if needed
        slidingWindowSize: 20
        failureRateThreshold: 40
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 10
        registerHealthIndicator: true
