spring:
  application:
    name: GREET-API
#For Admin server
  boot:
    admin:
      client:
        url: http://localhost:1111

#Commenting the server port for dynamic port insert in Load Balancing        
server:
  port: 9091

# For default Service registry (Eureka Server) for apis use port = 8761
#eureka:
#  client:
#    service-url:
#      defaultZone :http://localhost/8761/eureka

#For Enpoints Actuators 
management:
  endpoints:
    web:
      exposure:
        include: '*'
        