spring:
  application:
    name: 22_WebMVC_ToDoTaskApp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbms27
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true