spring:
  application:
    name: WELCOME-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
#Getting port from environment
#server:
#   port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'